### ISSUE TITLE
left shift error

### ISSUE THREAD

**Issue by dirknbr** [liyinxiao/LambdaRankNN#1]
I get this error, please check, does qid need to be particular type?

python3.7

```
bst7 = LambdaRankNN(input_size=X.shape[1], hidden_layer_sizes=(8,4,), activation=('relu', 'relu',), solver='adam')
qid = np.ones(len(train))
bst7.fit(X[train, :], y[train], qid)

Traceback (most recent call last):
  File "/home/dnachbar/python/lightgbm/zip.py", line 66, in <module>
    bst7.fit(X[train, :], y[train], qid)
  File "/home/dnachbar/.local/lib/python3.7/site-packages/LambdaRankNN/__init__.py", line 121, in fit
    X1_trans, X2_trans, y_trans, weight = self._transform_pairwise(X, y, qid)
  File "/home/dnachbar/.local/lib/python3.7/site-packages/LambdaRankNN/__init__.py", line 287, in _transform_pairwise
    original = ((1 << pos_label) - 1) * pos_loginv + ((1 << neg_label) - 1) * neg_loginv
TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by liyinxiao** [comment]
@dirknbr  It is more likely y[train] is your problem. Make sure y[train] is an integer, not float (such as numpy.float64).

**Comment by dirknbr** [comment]
thanks, y[train].astype(np.int64) fixed it
