### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by RadiantCrystal** [liyinxiao/LambdaRankNN#2]
I was trying to run the toy example given in the repo. It is showing below error

Traceback (most recent call last):
  File "lamdarank_test.py", line 14, in <module>
    ranker = LambdaRankNN(input_size=X.shape[1], hidden_layer_sizes=(16,8,), activation=('relu', 'relu',), solver='adam')
  File "/home/user/stellar_env/lib/python3.6/site-packages/LambdaRankNN/__init__.py", line 243, in __init__
    super(LambdaRankNN, self).__init__(input_size, hidden_layer_sizes, activation, solver)
  File "/home/user/stellar_env/lib/python3.6/site-packages/LambdaRankNN/__init__.py", line 31, in __init__
    self.model = self._build_model(input_size, hidden_layer_sizes, activation)
  File "/home/user/stellar_env/lib/python3.6/site-packages/LambdaRankNN/__init__.py", line 44, in _build_model
    input1 = Input(shape=(input_shape,), name='Input_layer1')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by liyinxiao** [comment]
This is probably due to tensorflow being incorrectly installed. 
A simple solution to bypass this problem is to switch to theano backend https://keras.io/backend/.
