### ISSUE TITLE
Not able to save model as pmml

### ISSUE THREAD

**Issue by agrawalgg** [liyinxiao/LambdaRankNN#3]
Traceback (most recent call last):
  File "/home/administrator/ilabs/GIT/learning2rank/rank/LR_testing.py", line 22, in <module>
    rankerNN2pmml(estimator=ranker.model, file='Model_example.xml', **params)
  File "/home/administrator/ilabs/GIT/learning2rank/.venv/lib/python3.6/site-packages/rankerNN2pmml/__init__.py", line 207, in rankerNN2pmml
    feature_names = _validate_inputs(estimator, transformer, feature_names)
  File "/home/administrator/ilabs/GIT/learning2rank/.venv/lib/python3.6/site-packages/rankerNN2pmml/__init__.py", line 29, in _validate_inputs
    raise TypeError("Provided model is not supported.")
TypeError: Provided model is not supported.

**Comment by liyinxiao** [comment]
You are getting this error because your ranker.model is not an instance of keras.models.Model. Please check your ranker.model, or look at my example in README.

**Comment by agrawalgg** [comment]
I have used the given example only for verification and getting the same error.
I am now able to  save model as a pickle file with a hack. so closing this thread.

**Comment by nmoraes513** [comment]
Same issue here! 
Traceback (most recent call last):
```
  File "test.py", line 25, in <module>
    rankerNN2pmml(estimator=ranker.model, file='Model_example.xml', **params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rankerNN2pmml/__init__.py", line 207, in rankerNN2pmml
    feature_names = _validate_inputs(estimator, transformer, feature_names)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rankerNN2pmml/__init__.py", line 29, in _validate_inputs
    raise TypeError("Provided model is not supported.")
TypeError: Provided model is not supported.
```
